### ISSUE TITLE
The app crashes when the timer finishes

### ISSUE THREAD

**Issue by amirrammari** [xujiangjiang/Easy-Cat-Timer#4]
The app crashes when the timer finishes when Windows Media Player is not installed.
I uninstalled Windows Media Player from Windows 10's Optional Features.
![Optional Features](https://user-images.githubusercontent.com/23485114/61574586-ff08c980-aad6-11e9-86fa-9c19340d56ea.png)
Please fix this bug.
Thanks.

**Comment by xujiangjiang** [comment]
Roger that! Thank you for your feedback!
I will fix this problem right away, just in these few days~

**Comment by xmha97** [comment]
In the first version: played button sound.
In v1.0.1.0: the app is completely silent and don't play any sound.
Of course, the problem of crashing the app was solved.

**Comment by xujiangjiang** [comment]
Thank you very much for your feedback~~~
Yes, this problem has still not been solved. But i recently thought of a solution~
This issue will be fixed in v1.0.2.
(probably a few days later)

**Comment by xujiangjiang** [comment]
I am very sorry, I have a very painful tooth for 2 weeks, so I went to the hospital and pulled my teeth.
I didn't recover until this week, so I didn't update it on time, I am very sorry.
I will solve this problem in the last few days~

**Comment by xmha97** [comment]
> I am very sorry, I have a very painful tooth for 2 weeks, so I went to the hospital and pulled my teeth.
> I didn't recover until this week, so I didn't update it on time, I am very sorry.
> I will solve this problem in the last few days~

It was sad to hear about your painful tooth.
Thank You Very Much

**Comment by xujiangjiang** [comment]
Wow, this thing is more complicated than I thought. I tried several methods and it was not very successful.
We need to set the volume and can't rely on WMP, which is very difficult.
Finally, we had to turn an audio into 5 audio to achieve the effect we wanted.
Therefore, the hard disk usage has changed from 3M to 15M, and the memory has increased by 2 times.
However, I think this is worth it because it works very well.
We still need a step and we can really succeed!
Next, I am going to judge if there is a WMP in the user's computer. If so, I will use the Media Player class to play the sound. If not, I use SoundPlayer to play sound effects.
(I updated a v1.0.1.1 version, but this version has not completely solved your problem. Your problem will be solved in v1.0.1.2.)
Thank you very much for your advice and support! I will continue to work hard!

哇……这个事情比我想象的更复杂，我试了几种方法，都不太成功。
我们既需要设置音量，但是又不能依赖于WMP，这很难。
最后，我们不得不把一个音频文件，变成5个音频文件，每个音频是不同的音量，这样勉强达到了我们想要的效果。
但也因为这样，硬盘占用从3M变为15M，内存增大了2倍。
不过，我觉得这是值得的，因为这样运行的非常好。
我们还需要一个步骤，就可以真正成功啦！
下一步，我准备判断用户电脑里是否安装有WMP软件。如果有，我就用Media Player类进行播放音效（完成时的音效）。如果没有，我就用SoundPlayer类播放音效（完成时的音效）。
（我更新了一个v1.0.1.1版本，但这个版本还没有完全解决你的问题。你的问题将在v1.0.1.2版本中，得到解决。）
非常感谢你的建议和支持！我会继续努力哒！

**Comment by xmha97** [comment]
Thank you for taking the time to resolve this issue. ❤
感谢您抽出宝贵时间来解决此问题。❤

**Comment by xmha97** [comment]
@xujiangjiang 
You solved this issue but didn't upload it to Steam.
Please update the Steam version to the last release.
您已解决此问题，但未将其上传到Steam。
请更新Steam版本至最新版本。
![image](https://user-images.githubusercontent.com/23485114/71871419-56a2fc00-312e-11ea-8e2e-a6697a27446a.png)
